name: Publish
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: "Build"
        run: |
          yarn --lockfile-freeze
          yarn build
          yarn --lockfile-freeze --production
          yarn version --no-git-tag-version --new-version $RELEASE_TAG_NAME
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}

      - name: "Setup npm token"
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: "Publish"
        run: yarn publish --tag $RELEASE_TARGET_BRANCH
        env:
          RELEASE_TARGET_BRANCH: latest
